
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'cespare/vim-toml'


[[plugins]] # *検索の拡張
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]] # コメントアウト機能
repo = 'tyru/caw.vim'

[[plugins]] # textobj
repo = 'kana/vim-textobj-user'

[[plugins]] # i, a,
repo = 'sgur/vim-textobj-parameter'

[[plugins]] # operator
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]] # 文書整形
repo = 'junegunn/vim-easy-align'

